### PR TITLE
ES6'ed your entire codebase ;)

### PR DESCRIPTION
**Pull request by FrontEndCoffee**
Used arrow syntax for functions

### CODE REVIEW

**Review by deecewan — APPROVED** [review]

**Comment by KoryNunn** [comment]
I'm extremely against this. 

Need more contributer opinions.

**Comment by FrontEndCoffee** [comment]
@KoryNunn please elaborate

**Comment by markdingemanse** [comment]
I personally feel that it improves the readability of the code. and its 2017 already.

**Comment by KoryNunn** [comment]
IMO arrows should only be used as lambdas, not top level/exported functions.

I have general disdain for syntactic flourish for flourishes sake. 

Or to put it more vaguely: (https://korynunn.github.io/jfwc)

I'm aware that my opinions do not represent the whole.

**Comment by FrontEndCoffee** [comment]
@KoryNunn Though I do see where you are coming from and I agree that in lambda type situations arrow functions should always be used, I strongly feel that there is a place for them outside of the lambda context. As a general rule of thumb: use it when it increases readability and thus decreases the chance of human errors occurring.

So to summarise: I think it is properly used in this situation, but for a larger codebase it probably wouldn't be a good idea.

**Comment by rgbkrk** [comment]
It is a bit too bad we didn't make this a named function originally for debugging purposes.

**Comment by rgbkrk** [comment]
> IMO arrows should only be used as lambdas, not top level/exported functions.

I tend to agree on this as well, especially if not named (aforementioned debugging issue). On the other hand, I want to welcome new contributions that don't change the major version drastically. We can always change it back as this is a backwards compatible change.

**Comment by marlonbernardes** [comment]
LGTCovfefed!

**Comment by benyitzhaki** [comment]
I totally covfefe it.

agree with @FrontEndCoffee. Even tho I'm not a great fan of arrow functions, I think they simplify the code in this kind of situations

**Comment by leosco** [comment]
Resisting ES6, especially for a new project is pretty silly, imo

**Comment by rgbkrk** [comment]
Needs a rebase

**Comment by rgbkrk** [comment]
Closing as this hasn't had any activity in a long time and no rebasing. Please make a new PR or re-open once rebased.

**Pull request closed without merging**
