### PR TITLE
here r u go

### PR DESCRIPTION
**Pull request by Qix-**
covfefe 4 lyf

for test:
```
npm i qix-/covfefe
```

covfefe

### CODE REVIEW

**Comment by rgbkrk** [comment]
I just watched the terminal video and it was amazing. Here's a clip for folks:

covfefe

Fuller video, with sound:

[covfefe.mp4.zip](https://github.com/rgbkrk/covfefe/files/1041877/covfefe.mp4.zip)

We will want this to remain backwards compatible for @binaryMuse's Atom extension, though we can always call it a major release. 😄

**Comment by Qix-** [comment]
tell me what to do and I shall do it :o

**Comment by rgbkrk** [comment]
When covfefe is called with no arguments, we should get this beautiful terminal art.

**Comment by Qix-** [comment]
good to go boss

<sup>FWIW this works better in iTerm2. I'm not entirely sure why.</sup>

**Comment by rgbkrk** [comment]
Shipped as 2.0.0

**Pull request merged**
